name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Specify Node.js versions to test against

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Or 'yarn' if the project uses Yarn

    - name: Install dependencies
      run: npm install

    # Optional: Add linting step if a linter is set up
    # - name: Lint
    #   run: npm run lint

    - name: Run tests and collect coverage
      run: npm run test # This will run c8 node --test as per package.json

    - name: Report coverage
      run: npx c8 report --reporter=lcov --reporter=text
